### ISSUE TITLE
Does not work with v3.4

### ISSUE THREAD

**Issue by KAMIKAZEUA** [CatalystApps/Cocos2dGAFPlayer#3]
Can't compile even. Cocos2D-Swift version 3.4.3 
![screen shot 2015-07-01 at 17 49 17](https://cloud.githubusercontent.com/assets/3391456/8457360/9b24534a-2019-11e5-8099-9c376090e5f3.png)
![screen shot 2015-07-01 at 17 49 26](https://cloud.githubusercontent.com/assets/3391456/8457361/9b51c8c0-2019-11e5-8a5c-ce11ef77e32b.png)
![screen shot 2015-07-01 at 17 49 35](https://cloud.githubusercontent.com/assets/3391456/8457362/9b54c750-2019-11e5-9c5c-7bfe6241c61c.png)
![screen shot 2015-07-01 at 17 49 44](https://cloud.githubusercontent.com/assets/3391456/8457363/9b59ac98-2019-11e5-8e44-fdcca3cb4854.png)

**Comment by SmartCat** [comment]
This library working only with cocos2d revision linked with (v2.1)

**Comment by KAMIKAZEUA** [comment]
And this https://github.com/CatalystApps/cocos2d-iphone-classic ?

**Comment by SmartCat** [comment]
Yes, it has fix for XCode >= 5.1.1

**Comment by KAMIKAZEUA** [comment]
I just need it for v3. Can you fix it?
