### ISSUE TITLE
Alpha Error

### ISSUE THREAD

**Issue by Yelles** [CatalystApps/Cocos2dGAFPlayer#5]
Hello, i'm testing your demo, it seems that transparency dont work (it's replaced by black color).

![img_0863](https://cloud.githubusercontent.com/assets/689478/12516383/7cf6e490-c12d-11e5-87d6-f010bef8fb63.PNG)

**Comment by SmartCat** [comment]
This version of GAF library developed for cocos2d ver2. What version of cocos are you using?

**Comment by Yelles** [comment]
I compiled just after running this commands :
$ git clone git://github.com/CatalystApps/Cocos2dGAFPlayer.git
$ git submodule update --init

So the cocos2d version is the external specified in the project : https://github.com/CatalystApps/cocos2d-iphone-classic

**Comment by SmartCat** [comment]
Hmmm... Did you use real device with ios >= 9.0 ?
If so, please check Library/Resources/Shaders/pcShader_PositionTextureAlpha_frag.fs

Please replace this block:
    //const float kMinimalAlphaAllowed = 0.01;

    vec4 texColor = texture2D(u_texture, v_texCoord);
    
    //texColor.a = max(texColor.a, kMinimalAlphaAllowed);   // to avoid division by 0

With this one:
    const float kMinimalAlphaAllowed = 0.01;

    vec4 texColor = texture2D(u_texture, v_texCoord);
    
    texColor.a = clamp(texColor.a, kMinimalAlphaAllowed, 1.0);   // to avoid division by 0

**Comment by Yelles** [comment]
thank you, it works!

iPhone 6S, iOS 9.2 (sorry I omitted this information)

**Comment by SmartCat** [comment]
Ok, thank you.
I've commit this change to repo
